# Generated by Django 4.1.1 on 2022-09-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='miportafolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
